[phases.setup]
nixPkgs = ["python312", "nodejs_22"]

[phases.install]
cmds = ["python3 -m venv /opt/venv && /opt/venv/bin/pip install -r backend/requirements.txt", "cd frontend && npx -y pnpm@latest install"]

[phases.build]
cmds = ["cd frontend && npx -y pnpm@latest run build"]

[start]
cmd = "./run.sh"
